/* Autogenerated by png2wx.pl on Mon Nov 11 12:35:11 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_radar_amber;
extern wxBitmap *_img_radar_amber_slave;
extern wxBitmap *_img_radar_amber_tt;
extern wxBitmap *_img_radar_blank;
extern wxBitmap *_img_radar_blank_slave;
extern wxBitmap *_img_radar_green;
extern wxBitmap *_img_radar_green_slave;
extern wxBitmap *_img_radar_green_tt;
extern wxBitmap *_img_radar_red;
extern wxBitmap *_img_radar_red_slave;
extern wxBitmap *_img_radar_amber_slave_tt;
extern wxBitmap *_img_radar_green_slave_tt;

#endif /* ICONS_H */
